name: Build

on:
  push:
    branches: [ C#6.0 ]
  pull_request:
    branches: [ C#6.0 ]

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: ['Debug', 'Release']

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild MinimalMVVM.sln -p:Configuration=${{matrix.configuration}}

