name: Build

on:
  push:
    branches: [ c#8.0 ]
  pull_request:
    branches: [ c#8.0 ]

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: ['Debug', 'Release']

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: dotnet build --configuration ${{matrix.configuration}} MinimalMVVM.sln
